name: wemapgl_platform_interface
description: A common platform interface for the wemapgl plugin.
version: 0.1.0
homepage: https://github.com/WEMAP-Official/WeMap-Flutter-SDK

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  http: ^0.12.0+4

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
